import Footer from './components/Footer/Footer';
import Header from './components/Header/Header';
import { ThemeProvider } from './context/ThemeContext';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header /> {children} <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
